### ISSUE TITLE
Less complex implementation: possibly faster.

### ISSUE THREAD

**Issue by thephoenixofthevoid** [Hedronium/event-multiplexer#3]
I just encountered your library and liked the idea. I noticed that there is a huge overhead: the need to store N * M listeners, where N, M -- numbers of events and objects respectively. 

I managed to come up with this (actually reformatted a bit to use your variable names where possible):
```js
import { EventEmitter } from 'events';

export const OBJECT_ADDED = Symbol('OBJECT_ADDED');
export const OBJECT_REMOVED = Symbol('OBJECT_REMOVED');

function handleRemoveListener(ev) {
    if (ev === "removeListener" || ev === "newListener") return;

    // 'removeListener' is emitted after the listener is removed.
    if (this.listenerCount(ev) == 0) {
        const l = this._listeners.get(ev);
        for (let obj of this._objects) obj.off(ev, l);
        this._listeners.delete(ev)
    }
}

function onNewListener(ev) { 
    if (ev === "removeListener"||ev === "newListener") return;

    // 'newListener' emitted before a listener is added to internal array
    if (this.listenerCount(ev) == 0) {
        const l = createListener(this, ev)
        for (let obj of this._objects) obj.on(ev, l);
        this._listeners.set(ev, l)
    }
}

function createListener(mpx, event) {
    return function listener(...args) {
        mpx.emit(event, this, ...args)
    }
}

export class EventMultiplexer extends EventEmitter {

    _objects = new Set();
    _listeners = new Map();

    constructor() {
        super();
        this.on('removeListener', handleRemoveListener);
        this.on('newListener',    onNewListener);
    }

    add(obj) {
        if (this._objects.has(obj)) return;
        this._objects.add(obj);
        this._listeners.forEach((fn, ev) => obj.on(ev, fn))
        this.emit(OBJECT_ADDED, obj);
    }
    
    remove(obj) {
        if (!this._objects.has(obj)) return;
        this._objects.delete(obj);
        this._listeners.forEach((fn, ev) => obj.off(ev, fn))
        this.emit(OBJECT_REMOVED, obj);
    }   

    // For tests
    addMany   (...objs) { objs.map(this.add.bind(this))    }
    removeMany(...objs) { objs.map(this.remove.bind(this)) }
}
```

The only "drawback" is reliance on `this` context.

**Comment by omranjamal** [comment]
Hey, I really appreciate the time you took to rewrite the library, at the moment very busy with my day job will look over this over the weekend and provide comprehensive feedback.

This particular piece of code does fail a few of the test cases and as far as I remember the test cases were tied to our requirements so over the weekend I'll reevaluate our requirements and validity of our tests.

That being said the code you wrote is beautiful and it's very temping to just paste this in and push.

**Comment by thephoenixofthevoid** [comment]
Maybe, isn't it because I made "add" and "remove" accept a single argument, and created separate methods for the original semantics? Then just rename either:
1) Methods in tests
2) add -> addOne, addMany->add. The same about remove.
to pass the tests. 

The reason I made primary methods accept only a single argument is to avoid creating unneeded closures or loops, as well as avoid most likely deoptimization by V8 when two or more arguments are used for the first time. IMHO, when the number of instances to add is known and small (1-3, for example), they'd be better added through multiple calls.

Please let me know if that helps with tests.

**Comment by omranjamal** [comment]
I did update those haha, thanks for explaining the reasoning behind it though, that was very insightful. I think there must be a very tiny one liner missing somewhere or a bug within my tests themselves that is causing it to report that the listener added by the library is not removed after removing the object from the mux.

I'll look into it. Thanks again!

**Comment by omranjamal** [comment]
Hey! You're right, and I was right, this is absolutely beautiful. I'd hate for the commit with this code to have my username. Please send a pull request! This is awesome!
